### ISSUE TITLE
Enable the ability to enable/disable existing rules

### ISSUE THREAD

**Issue by drahamim** [chef-cookbooks/windows_firewall#23]
The cookbook currently only creates rules. I would be great if it also had the ability to enable/disable rules.

**Comment by akhileshvishwanath** [comment]
Yes, were you able get it?

**Comment by drahamim** [comment]
@akhileshvishwanath the final solution was to use 
``` 
netsh_firewall_rule 'RULE_NAME' do
    action :enable
end

**Comment by tas50** [comment]
This will be resolved in the next release
