### ISSUE TITLE
Packaged version of windows_firewall.tgz on supermarket contains .git file

### ISSUE THREAD

**Issue by awill1** [chef-cookbooks/windows_firewall#24]
The packaged version of windows_firewall.tgz on supermarket contains a .git file. This file is not in the lynx44/windows_firewall git repository. 

This file causes issues for me when doing a knife cookbook site install windows_firewall because the gitpath contained in the .git file does not match my repository path. My chef directory is a subdirectory in my git repository.

There is a chefignore file that contains .git but somehow the .git made it into the tgz hosted by chef supermarket.

**Comment by tas50** [comment]
This should be resolved with the 4.0 release which was done with stove.
