### ISSUE TITLE
Configuration of firewall rules are not idempotent

### ISSUE THREAD

**Issue by mattstratton** [chef-cookbooks/windows_firewall#9]
Firewall rules are created if missing, but not updated if their parameters do not match the ones declared in the attributes.

**Comment by mattstratton** [comment]
There are a couple ways to handle this.

Could add a `:config` action, and then you would do `:add` and/or `:config` depending on what you wanted (this pattern is used in the [opscode-cookbooks/iis](http://github.com/opscode-cookbooks/iis) cookbook

another option is to add an action called `:create_if_missing`. Should talk to find out what is the best pattern.

**Comment by drahamim** [comment]
any updates on this? or should I just use a different cookbook.

**Comment by lynx44** [comment]
I'm happy to accept pull requests regarding this issue. At this point in time, I'm not able to dedicate much time to this project due to other priorities, but any contributions would be considered and greatly appreciated!

**Comment by tas50** [comment]
This will be resolved in the next release
